spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
# kêt nối database
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=cinema_app;encrypt=true;trustServerCertificate=true;
    username: sa
    password: 123456
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
  sendgrid:
    api-key: xxx xxx xxx
    from-email: admin@em7802.cineman.io.vn
    template-id: d-c59a7109d01d40ca97cd20310ad512f7
    verification-link: http://localhost:8081/user/confirm-email
jwt:
  expirationDay: 30
  expirationMinutes: 30
  expirationVerify: 10
  accessKey: XEV3ZWGVjFHgilOWNuKJxNRSK8wUl5txZH3JabLRtfw=
  refreshKey: LGgDK8nPs6LeCAkBUmTwjCxJo7EUHs0Djs63XCBNpaCbYZTIagsltVFa8p6ltllN
  verifyKey: blIDNZ3afjxIxnJ6Rj/EtbD3p4znONpL6Y//xEQoaQ8=

api:
  path: /api/v01
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: cineman
    server: http://localhost:${server.port}
    title: Cineman Backend service
    version: 1.0.0
