spring:
  config:
    activate:
      on-profile: prod
  devtools:
    add-properties: true
  flyway:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/cineman
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
jwt:
  secretKey: sonProduct15@2
