spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
# kêt nối database
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=cineman;encrypt=true;trustServerCertificate=true;
    username: sa
    password: Son15@2
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: cineman
    server: http://localhost:${server.port}
    title: Cineman Backend service
    version: 1.0.0

jwt:
  secretKey: son15@2

  spring:
    jpa:
      hibernate:
        ddl-auto=none: