spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: giamsatson@gmail.com
    password: fvgy bywn ozwr qxqm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            protocols: TLSv1.2
  flyway:
    locations: classpath:/db/migration,classpath:/dev/db/migration
    baseline-on-migrate: true
    baseline-version: 0
    enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 313620644939-tv7e1h8s17cpj07s732bp029joi11dg1.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:3000/auth/google/callback
        provider:
          google:
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
  datasource:
    url: jdbc:postgresql://localhost:5432/cineman
    username: java
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: false
  sendgrid:
    api-key: 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
    from-email: sondoquang3@gmail.com
    template-id: d-35719691e618440abf276a0f43260d7b
    verification-link: http://localhost:8081/api/v01/auth/confirm-email
jwt:
  expirationDay: 30
  expirationMinutes: 30
  expirationVerify: 10
  accessKey: XEV3ZWGVjFHgilOWNuKJxNRSK8wUl5txZH3JabLRtfw=
  refreshKey: LGgDK8nPs6LeCAkBUmTwjCxJo7EUHs0Djs63XCBNpaCbYZTIagsltVFa8p6ltllN
  verifyKey: blIDNZ3afjxIxnJ6Rj/EtbD3p4znONpL6Y//xEQoaQ8=
cinema:
  upload_file:
    base_path: file:///D:/1.FPT-College/DATN/backend/cineman/uploads
api:
  path: /api/v01
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: cineman
    server: http://localhost:${server.port}
    title: Cineman Backend service
    version: 1.0.0
google:
  service:
    account:
      key: classpath:service_account.json
vnpay:
  pay-url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
  return-url: "http://localhost:3000/payment/payment-callback"
  tmn-code: "EKKOO4T6"
  secret-key: "LUVS2LLREFB2OB86U53EQ9W5DCSFZ69E"
  api-url: "https://sandbox.vnpayment.vn/merchant_webapi/api/transaction"
