spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  # kêt nối database
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=cineman_system;encrypt=true;trustServerCertificate=true;
    username: sa
    password: 123456
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
jwt:
  secretKey: sonProduct15@2

