spring:
  config:
    activate:
      on-profile: docker
  flyway:
    enabled: false
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/cineman}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

cinema:
  upload_file:
    base_path: ${CINEMA_UPLOAD_FILE_BASE_PATH:file:///app/uploads}

openapi:
  service:
    server: ${BACKEND_SERVICE:http://localhost:${server.port}}
