spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  servlet:
    multipart:
      max-file-size: 10MB     # Giới hạn cho 1 file
      max-request-size: 20MB  # Tổng dung lượng toàn request
# kêt nối database
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=cinema_app_test;encrypt=true;trustServerCertificate=true;
    username: sa
    password: 123456

    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: false
  sendgrid:
    api-key: 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
    from-email: admin@em7802.cineman.io.vn
    template-id: d-c59a7109d01d40ca97cd20310ad512f7
    verification-link: http://localhost:8081/api/v01/auth/confirm-email
jwt:
  expirationDay: 30
  expirationMinutes: 15
  expirationVerify: 10
  accessKey: XEV3ZWGVjFHgilOWNuKJxNRSK8wUl5txZH3JabLRtfw=
  refreshKey: LGgDK8nPs6LeCAkBUmTwjCxJo7EUHs0Djs63XCBNpaCbYZTIagsltVFa8p6ltllN
  verifyKey: blIDNZ3afjxIxnJ6Rj/EtbD3p4znONpL6Y//xEQoaQ8=

api:
  path: /api/v01
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: cineman
    server: http://localhost:${server.port}
    title: Cineman Backend service
    version: 1.0.0


google:
  service:
    account:
      key: classpath:service_account.json

