spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
# kêt nối database
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=cinema_app_db;encrypt=true;trustServerCertificate=true;
    username: sa
    password: 123456
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: false
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: cineman
    server: http://localhost:${server.port}
    title: Cineman Backend service
    version: 1.0.0

jwt:
  secretKey: son15@2
  accessKey: CnqL6dU1T1mWMd6O1ltlO4HtD7IvjPMjNvsJTK2FcOg=
  refreshKey: zZQbpaqG2bzY2MJ2BD4uIoyC4cRs2jgpAxg38o9LT00=
  expiryHours: 24
  expiryMinute: 5

  spring:
    jpa:
      hibernate:
        ddl-auto=none:

