CREATE TABLE IF NOT EXISTS promotion_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    status BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_promotion_types_code UNIQUE (code),
    CONSTRAINT uk_promotion_types_name UNIQUE (name)
);

ALTER TABLE IF EXISTS promotions
    ADD COLUMN IF NOT EXISTS promotion_type_id BIGINT;

DO $$
BEGIN
    IF to_regclass('promotions') IS NOT NULL
        AND to_regclass('promotion_types') IS NOT NULL
        AND NOT EXISTS (
            SELECT 1
            FROM pg_constraint c
            JOIN pg_attribute a
                ON a.attrelid = c.conrelid
               AND a.attnum = ANY (c.conkey)
            WHERE c.conrelid = 'promotions'::regclass
              AND c.contype = 'f'
              AND a.attname = 'promotion_type_id'
        ) THEN
        ALTER TABLE promotions
            ADD CONSTRAINT fk_promotions_promotion_type
                FOREIGN KEY (promotion_type_id)
                REFERENCES promotion_types(id);
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS promotion_membership_ranks (
    promotion_id BIGINT NOT NULL,
    membership_rank_id INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (promotion_id, membership_rank_id),
    CONSTRAINT fk_promotion_membership_ranks_promotion
        FOREIGN KEY (promotion_id) REFERENCES promotions(promotion_id) ON DELETE CASCADE,
    CONSTRAINT fk_promotion_membership_ranks_membership_rank
        FOREIGN KEY (membership_rank_id) REFERENCES membership_ranks(id) ON DELETE CASCADE
);
