CREATE TABLE IF NOT EXISTS movie_variations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    status BOOLEAN NOT NULL DEFAULT TRUE
);

ALTER TABLE IF EXISTS movies
    ADD COLUMN IF NOT EXISTS movie_variation_id INTEGER;

DO $$
BEGIN
    IF to_regclass('movies') IS NOT NULL
        AND to_regclass('movie_variations') IS NOT NULL
        AND NOT EXISTS (
            SELECT 1
            FROM pg_constraint c
            JOIN pg_attribute a
                ON a.attrelid = c.conrelid
               AND a.attnum = ANY (c.conkey)
            WHERE c.conrelid = 'movies'::regclass
              AND c.contype = 'f'
              AND a.attname = 'movie_variation_id'
        ) THEN
        ALTER TABLE movies
            ADD CONSTRAINT fk_movies_movie_variations
                FOREIGN KEY (movie_variation_id)
                REFERENCES movie_variations (id);
    END IF;
END $$;