ALTER TABLE movie_variations
DROP CONSTRAINT UQ__movie_va__72E12F1B881BE6D2

ALTER TABLE movie_variations
ALTER COLUMN name NVARCHAR(100) NOT NULL;

ALTER TABLE movie_variations
ADD CONSTRAINT UQ__movie_va__72E12F1B881BE6D2 UNIQUE (name);