ALTER TABLE IF EXISTS promotions
    ADD COLUMN IF NOT EXISTS quantity INTEGER NOT NULL DEFAULT 1;

ALTER TABLE IF EXISTS promotions
    ADD COLUMN IF NOT EXISTS limit_amount NUMERIC(10,2) NOT NULL DEFAULT 1;