CREATE TABLE IF NOT EXISTS membership_ranks (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    required_point INTEGER NOT NULL,
    return_points_ticket DOUBLE PRECISION NOT NULL,
    return_points_snack DOUBLE PRECISION NOT NULL,
    priority_level INTEGER NOT NULL DEFAULT 0,
    status BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_membership_ranks_priority_level_non_negative CHECK (priority_level >= 0),
    CONSTRAINT ck_membership_ranks_required_point_non_negative CHECK (required_point >= 0),
    CONSTRAINT ck_membership_ranks_return_points_ticket_non_negative CHECK (return_points_ticket >= 0),
    CONSTRAINT ck_membership_ranks_return_points_snack_non_negative CHECK (return_points_snack >= 0)
);

ALTER TABLE IF EXISTS users
    ADD COLUMN IF NOT EXISTS rank_id INTEGER;

DO $$
BEGIN
    IF to_regclass('users') IS NOT NULL
        AND to_regclass('membership_ranks') IS NOT NULL
        AND NOT EXISTS (
            SELECT 1
            FROM pg_constraint c
            JOIN pg_attribute a
                ON a.attrelid = c.conrelid
               AND a.attnum = ANY (c.conkey)
            WHERE c.conrelid = 'users'::regclass
              AND c.contype = 'f'
              AND a.attname = 'rank_id'
        ) THEN
        ALTER TABLE users
            ADD CONSTRAINT fk_users_rank
                FOREIGN KEY (rank_id)
                REFERENCES membership_ranks(id);
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS user_point_histories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    invoice_id BIGINT NOT NULL,
    change_point INTEGER NOT NULL,
    reason VARCHAR(200) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_point_histories_users
        FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT fk_user_point_histories_invoices
        FOREIGN KEY (invoice_id) REFERENCES invoices(invoice_id)
);

DROP TABLE IF EXISTS social_accounts;

ALTER TABLE IF EXISTS snacks
    ALTER COLUMN unit_price TYPE NUMERIC(10,2),
    ALTER COLUMN unit_price SET NOT NULL;

DO $$
BEGIN
    IF to_regclass('snacks') IS NOT NULL
        AND NOT EXISTS (
            SELECT 1
            FROM pg_constraint
            WHERE conrelid = 'snacks'::regclass
              AND contype = 'c'
              AND pg_get_constraintdef(oid) ILIKE '%unit_price >= 0%'
        ) THEN
        ALTER TABLE snacks
            ADD CONSTRAINT ck_snacks_unit_price_non_negative
                CHECK (unit_price >= 0);
    END IF;
END $$;

ALTER TABLE IF EXISTS detail_booking_snacks
    ADD COLUMN IF NOT EXISTS total_price NUMERIC(10,2) NOT NULL DEFAULT 0;

ALTER TABLE IF EXISTS invoices
    ADD COLUMN IF NOT EXISTS total_amount NUMERIC(10,2);

ALTER TABLE IF EXISTS users
    DROP COLUMN IF EXISTS user_type;